### ISSUE TITLE
Automatic display suppresses content on start page

### ISSUE THREAD

**Issue by cmb69** [cmb69/themeswitcher_xh#1]
See http://cmsimpleforum.com/viewtopic.php?f=16&t=8487#p46261.

**Comment by manu37** [comment]
I don't get into it. Why is the startpage not shown with themeswitcher_xh? Themeswitcher doesn't touch $s, only prepends $o (by the select field).

**Comment by cmb69** [comment]
> Why is the startpage not shown with themeswitcher_xh?

That's because of [these lines](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0/cmsimple/cms.php#L1263-L1266); if `$o != ''` `$s` stays `-1`. A workaroung (which I don't like, though) is to preprend to `$c[$pd_s]` instead of appending to `$o`.

**Comment by manu37** [comment]
> That's because of these lines ...

This is really poor design which we should solve soon. Even if I have a patch ready, shall we wait with the themeswitcher in the demo page until this is fixed?

**Comment by cmb69** [comment]
> This is really poor design which we should solve soon.

I agree (see cmsimple-xh/cmsimple-xh#35). However, changing this would affect plugins which use "intrinsic" pages, such as Register's logged-in page (and there are many more). The basic idea of this code is that plugins can catch an arbitrary URL without "page URL" and use that for whatever purpose they desire. I'm afraid changing this would cause a lot of incompatibilities – not as much as cmsimple-xh/cmsimple-xh#21, but the fix would be much harder. As preliminary step, we should come up with a forward compatible way for plugins to use such "intrinsic" pages (`function`, $f'`?) It might be best to offer some abstraction.

PS: Oops – I've forgot to mention that the plugin administration usually consists of such "intrinsict" pages…

**Comment by manu37** [comment]
Here is a possible patch to get this run. 
[patches.zip](https://github.com/cmb69/themeswitcher_xh/files/1266042/patches.zip)
there is also another patch to get themeswitcher_xh run in dev environment.
regards manu

**Comment by cmb69** [comment]
> Here is a possible patch to get this run.

Thanks. This would suppress the themeswitcher selectbox on some "intrinsic" pages like sitemap and mailform, though. Therefore the solution in 77e4fc2 appears to be preferable (but is still not perfect).

**Comment by cmb69** [comment]
> there is also another patch to get themeswitcher_xh run in dev environment.

Thanks, again. I think the whole guarding code can simply be removed – in hindsight that wasn't be the best idea, anyway.

**Comment by manu37** [comment]
Here's another addition to suppress theme selection on login page:
[patch.zip](https://github.com/cmb69/themeswitcher_xh/files/1266987/patch.zip)

**Comment by cmb69** [comment]
> Here's another addition to suppress theme selection on login page:

Why should the selectbox be hidden on the login page?

**Comment by manu37** [comment]
Because I want to login - newly on a seperate page - not to change theme. And then I land on the start page again, that's confusing.

**Comment by cmb69** [comment]
> And then I land on the start page again, that's confusing.

Indeed, that's close to a bug, and should be fixed. See #17.
