### ISSUE TITLE
Malfunction in XH 1.6.10

### ISSUE THREAD

**Issue by ghost** [cmb69/themeswitcher_xh#15]
XH 1.6.10 : Themeswitcher_XH detected an unsupported CMSimple_XH version.
Uninstall Themeswitcher_XH or upgrade to a supported CMSimple_XH version!

Beta 1 geht auch nicht

**Comment by cmb69** [comment]
Hmm, I can't reproduce this – neither with Themeswitcher_XH 1.0beta2 nor with current master.

At least as quick-fix you can remove [these lines](https://github.com/cmb69/themeswitcher_xh/blob/1.0beta2/index.php#L22-L36).

**Comment by ghost** [comment]
Ich habe jetzt xh1.6.10 dreimal unter Xamp mit php5.6 neu in neuem Verzeichnis installiert (Alles neu heruntergeladen und nur zuätzlich den Themeswitcher.)
Entweder zeigt der Switcher das Konfigurations-Menü nicht(erste Installation gestern, dann zeigt er korrekt CMSimple_XH 1.6.10  Released: 2017-06-18 an), oder er wirft obigen Fehler(meistens). Unter XH1.67 geht alles.
Das /*  hilft zwar, aber  ich sehe dann unter Info "@CMSIMPLE_XH_VERSION@  Released: @CMSIMPLE_XH_DATE@" ohne Zahlen. Der Rest des CMS geht.
(Bilder hochladen geht irgendwie nicht)

**Comment by cmb69** [comment]
> Das /* hilft zwar, aber ich sehe dann unter Info "@CMSIMPLE_XH_VERSION@ Released: 

Dann hast Du den Quellcode von CMSimple_XH installiert, und nicht eines der offiziellen Pakete, die es für [1.6 auf SourceForge](https://sourceforge.net/projects/cmsimplexh/files/CMSimple_XH/CMSimple_XH%201.6/) und für [1.7 auf Github](https://github.com/cmsimple-xh/cmsimple-xh/releases) gibt (nicht "Source code").
