### ISSUE TITLE
Dont show all templates

### ISSUE THREAD

**Issue by ghost** [cmb69/themeswitcher_xh#7]
To show only a selection of templates  my proposal is to make a -- or a == before the directory name of those which should stay invisible for the visitor (like:  --modern) - This should be easy to code.

It is useful if a template like the one  for the startsite or for a special site should not be chosen otherwise

**Comment by cmb69** [comment]
That might be even better than #5. I'm not sure about the prefix, though.

Anyhow, you can use a `.` as prefix, and it already works (i.e. such templates will not be shown in the select box, but can be used in the configuration manually, i.e. via `config.php`).
